package {{ .PackageName }}


type ServiceGroup struct {
    // Code generated by github.com/haoleiqin/gin-flip-api Begin; DO NOT EDIT.

	// Code generated by github.com/haoleiqin/gin-flip-api End; DO NOT EDIT.
}

