package autocode

type ApiGroup struct {
	// Code generated by github.com/haoleiqin/gin-flip-api Begin; DO NOT EDIT.
	AutoCodeExampleApi
	// Code generated by github.com/haoleiqin/gin-flip-api End; DO NOT EDIT.
}
